# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = []
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 3
name = "Orion"
service_id = "92b3mTmHFX7iwhlsjzmosj"
[scripts]
  build = "$(npm prefix)/node_modules/.bin/js-compute-runtime src/index.ts bin/main.wasm"

[local_server]
  host = "127.0.0.1"
  port = 7676
  [local_server.backends]
    [local_server.backends.graphql-server]
      url = "https://pcq8dgfxoi.execute-api.us-east-1.amazonaws.com"

   [local_server.env_vars]
    FASTLY_COMPUTE_CUSTOM_DOMAIN = "pcq8dgfxoi.execute-api.us-east-1.amazonaws.com"

[setup.backends.graphql-server]
  description = "GraphQL Origin Server"
  address = "3a5izbdkp7.execute-api.us-east-1.amazonaws.com"
  port = 443
  use_ssl = true
  ssl_cert_hostname = "3a5izbdkp7.execute-api.us-east-1.amazonaws.com"
  ssl_sni_hostname = "3a5izbdkp7.execute-api.us-east-1.amazonaws.com"
